export const IPC_CHANNELS = {
  APP_GET_LAUNCH_STATE: "app:get-launch-state",
  DOCUMENT_OPEN: "document:open",
  DOCUMENT_LIST_RECENT: "document:list-recent",
  DOCUMENT_READ_BINARY: "document:read-binary",
  DOCUMENT_UPDATE_PROGRESS: "document:update-progress",
  LIBRARY_LIST_SNAPSHOT: "library:list-snapshot",
  LIBRARY_CREATE_FOLDER: "library:create-folder",
  LIBRARY_RENAME_FOLDER: "library:rename-folder",
  LIBRARY_MOVE_DOCUMENT: "library:move-document",
  TRANSLATE_TEXT: "translate:text",
  FORMULA_RECOGNIZE: "formula:recognize",
  FORMULA_EXPLAIN: "formula:explain",
  FORMULA_LIST_BY_DOCUMENT: "formula:list-by-document",
  FORMULA_GET_BY_ID: "formula:get-by-id",
  NOTE_SAVE: "note:save",
  NOTE_LIST_BY_DOCUMENT: "note:list-by-document",
  NOTE_DELETE: "note:delete",
  EXPORT_MARKDOWN: "export:markdown",
  HISTORY_LIST: "history:list",
  SETTINGS_SAVE_AI: "settings:save-ai",
  SETTINGS_GET_AI: "settings:get-ai",
  SETTINGS_SAVE_MATHPIX: "settings:save-mathpix",
  SETTINGS_GET_MATHPIX: "settings:get-mathpix",
  SETTINGS_TEST_MATHPIX: "settings:test-mathpix",
  SETTINGS_SAVE_PIX2TEX: "settings:save-pix2tex",
  SETTINGS_GET_PIX2TEX: "settings:get-pix2tex",
  SETTINGS_TEST_PIX2TEX: "settings:test-pix2tex",
  SETTINGS_SAVE_FORMULA_OCR: "settings:save-formula-ocr",
  SETTINGS_GET_FORMULA_OCR: "settings:get-formula-ocr",
  SETTINGS_SAVE_HOVER_TRANSLATE: "settings:save-hover-translate",
  SETTINGS_GET_HOVER_TRANSLATE: "settings:get-hover-translate",
  SETTINGS_SAVE_THEME: "settings:save-theme",
  SETTINGS_GET_THEME: "settings:get-theme",
  DIALOG_PICK_PDF: "dialog:pick-pdf",
  FILE_SAVE_FORMULA_IMAGE: "file:save-formula-image",
  APP_MENU_ACTION: "app:menu-action",
  MENU_UPDATE_RECENT_DOCUMENTS: "menu:update-recent-documents",
} as const;

export type IpcChannel = (typeof IPC_CHANNELS)[keyof typeof IPC_CHANNELS];
